### PR TITLE
Add `Options` support

### PR DESCRIPTION
**Pull request by zwilias**
- [x] Properly hash the e-mail (trim + lowercase)
- [x] Allow passing only the allowed options and handle them
- [x] Provide sane defaults
- [x] Allow overriding only the needed options

### CODE REVIEW

**Comment by kuzzmi** [comment]
It's not just `Options` ;) Great improvement, looks awesome

**Comment by zwilias** [comment]
I ended up renaming the main functions to `img` and `url`, since it makes sense to use them qualified: `Gravatar.url` and `Gravatar.img` :)

**Comment by kuzzmi** [comment]
@zwilias Agree. Naming is hard, I was just using these names in my code. Package is bumped and published already.

**Comment by zwilias** [comment]
You should probably:
- Update the README.md
- tag your release
- push that tag

https://medium.com/@Max_Goldstein/how-to-publish-an-elm-package-3053b771e545 <- useful resource :)

**Pull request merged**
